version: "3.8"

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./web/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  push_db:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: "no"
    depends_on:
      - db
    command: npx prisma db push
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
