name: 'Deployment Procedure'
description: 'Common deployment steps'
runs:
  steps:
    
    - name: Move checked-out code to production folder
      run: |
        rsync -av --progress $GITHUB_WORKSPACE/ /home/heiguser/onlinetest/ --exclude .git

    - name: Generate environment files
      run: |
        cd /home/heiguser/onlinetest
        echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/onlinetest" > web/.env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> web/.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> web/.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> web/.env
        echo "GITHUB_ORG=heigvd-teaching-tools" >> web/.env
        echo "GITHUB_APP_ID=${{ secrets.GH_APP_ID }}" >> web/.env
        echo "GITHUB_APP_PRIVATE_KEY_PATH=eval-teaching-tools.private-key.pem" >> web/.env
        echo "GITHUB_APP_INSTALLATION_ID=${{ secrets.GH_APP_INSTALLATION_ID }}" >> web/.env

        echo "NEXTAUTH_URL=https://eval.iict-heig-vd.in" > web/.env.production
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> web/.env.production
        echo "NEXTAUTH_GITHUB_ID=${{ secrets.NEXTAUTH_GITHUB_ID }}" >> web/.env.production
        echo "NEXTAUTH_GITHUB_SECRET=${{ secrets.NEXTAUTH_GITHUB_SECRET }}" >> web/.env.production
        echo "DB_SANDBOX_CLIENT_HOST=172.17.0.1" >> web/.env.production

    - name: Generate GitHub App private key and ssl certificates
      run: |
        cd /home/heiguser/onlinetest
        mkdir -p web
        echo "${{ secrets.GH_APP_PRIVATE_KEY }}" > web/eval-teaching-tools.private-key.pem

        mkdir -p ssl
        echo "${{ secrets.SSL_FULLCHAIN }}" > ssl/fullchain.pem
        echo "${{ secrets.SSL_PRIVKEY }}" > ssl/privkey.pem
        
    - name: Build Custom Docker images
      run: |
        cd /home/heiguser/onlinetest
        docker build -t custom-sqlfluff ./docker-images/custom-sqlfluff

    - name: Build Docker Compose Images
      run: |
        cd /home/heiguser/onlinetest
        docker compose build

    - name: Start Docker Compose Services
      run: |
        cd /home/heiguser/onlinetest
        docker compose up -d

    - name: Run Prisma Migrations
      run: |
        cd /home/heiguser/onlinetest
        container_id=$(docker ps -qf "name=onlinetest-web-")
        docker exec $container_id npx prisma migrate deploy

