version: "3.8"
name: eval
services:
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - assets:/app/assets
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15.0
    restart: unless-stopped
    env_file:
      - ./db/.env.db.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:
  assets:

networks:
  app-network:
    driver: bridge
