name: Deploy Dispatch

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment Target? (PROD or STAGE)'     
        required: true
        default: 'PROD'

jobs:
  deploy_to_prod:
    runs-on: [self-hosted, prod-runner]
    if: github.event.inputs.target == 'PROD'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PROD
        uses: ./.github/actions/deploy
        with:
          
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          NEXTAUTH_URL: https://eval.iict-heig-vd.in
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_ID }}
          NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}

  deploy_to_stage:
    runs-on: [self-hosted, stage-runner]
    if: github.event.inputs.target == 'STAGE'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to STAGE
        uses: ./.github/actions/deploy
        with:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          NEXTAUTH_URL: https://192.168.1.224
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_GITHUB_ID: ${{ secrets.NEXTAUTH_GITHUB_SECRET }}
          NEXTAUTH_GITHUB_SECRET: ${{ secrets.NEXTAUTH_GITHUB_SECRET_STAGE }}
          SSL_FULLCHAIN: ${{ secrets.SSL_FULLCHAIN }}
          SSL_PRIVKEY: ${{ secrets.SSL_PRIVKEY }}
          

